### ISSUE TITLE
有關於食物辨識predict.py 的執行問題

### ISSUE THREAD

**Issue by shangxiwu** [andywu0913/Chinese-Cafeteria-Food-Recognition#1]
您好
不好意思打擾您，我在github上看到您的專題，覺得蠻有興趣的，我試著在ubuntu上用虛擬環境，將您上面所列出的套件依須版本安裝，執行predict.py,  
我下的指令為 python predict.py -c config.json -i data/test/imgs/img_73.jpg -o data/output/1
但出現錯誤訊息如附檔所示, 
![執行畫面](https://user-images.githubusercontent.com/67216779/92297090-25edbd80-ef6e-11ea-8d08-4d02e61f536e.JPG)

能否請問除了您建議的套件及版本(我python為3.7.9), 是否有其它的套件須要安裝, 還是環境上有些問題呢?  感謝您!
Python 3.7
NumPy 1.16.0
Tensorflow 1.13.2
Keras 2.2.5
OpenCV (not version dependent)
tqdm (not version dependent)

**Comment by andywu0913** [comment]
錯誤訊息是與載入train好的weight檔有關
請問你在config檔裡面的`saved_weights_name`設定的檔案路徑與名稱與weight檔所在的路徑與名稱有一致嗎

**Comment by shangxiwu** [comment]
請問您指的是在config.json 裡的"saved_weights_name":   "cafeteria.h5"  這個檔案的路徑嗎?
我檔案跟資料夾是保持與您同樣結構，沒有更改，直接執行 config.json，是否是這樣產生問題呢?

**Comment by shangxiwu** [comment]
您好, 我發現我原本的問題是cafeteria.h5 檔案是空的，所以再重新下載一次，己經可以辨識，照成你的困擾，不好意思。您的專題蠻有趣的，如果有機會再跟您請教。

**Comment by andywu0913** [comment]
不客氣^^
問題有解決就好
本人目前還在服四個月的軍事訓練役，所以只有休假才能看訊息回訊息

**Comment by andywu0913** [comment]
> 您好, 我發現我原本的問題是cafeteria.h5 檔案是空的，所以再重新下載一次，己經可以辨識，照成你的困擾，不好意思。您的專題蠻有趣的，如果有機會再跟您請教。

不客氣^^
問題有解決就好
本人目前還在服四個月的軍事訓練役，所以只有休假才能看訊息回訊息

**Comment by shangxiwu** [comment]
您好， 再請教您一個問題，我在config.json 新加入幾樣類別及一些label好的照片, 將cafeteria.h5移除後，再重新training, 完成後
後跑predict.py時，顯示 ValueError: Cannot create group in read-only mode. 的訊息, 看網路上相關error的解釋有提到如果train時使用 model.save_weights只保存模型的參數，但並沒有保存模型的圖結構, 如果用model.save( )保存下來的h5才可以直接通過load_model()打開！我把錯誤訊息放於附檔, 不知道這是不是主要的原因， 請問你當時有遇到類似的問題嗎? 再麻煩您了。感謝。 
![Error](https://user-images.githubusercontent.com/67216779/94107963-07922800-fe71-11ea-9a24-245937953a32.JPG)

**Comment by andywu0913** [comment]
> 您好， 再請教您一個問題，我在config.json 新加入幾樣類別及一些label好的照片, 將cafeteria.h5移除後，再重新training, 完成後
> 後跑predict.py時，顯示 ValueError: Cannot create group in read-only mode. 的訊息, 看網路上相關error的解釋有提到如果train時使用 model.save_weights只保存模型的參數，但並沒有保存模型的圖結構, 如果用model.save( )保存下來的h5才可以直接通過load_model()打開！我把錯誤訊息放於附檔, 不知道這是不是主要的原因， 請問你當時有遇到類似的問題嗎? 再麻煩您了。感謝。

應該是唷
`model.save()`配的是`load_model()`
`model.save_weights()`配的是`model.load_weights()`

兩者差在一個有把結構也存下來一個則無
